gem "json", ">= 2.0.0", "!=2.7.0", platforms: [:windows, :jruby]
gem "error_highlight", ">= 0.4.0", platforms: :ruby
gem "sdoc", git: "https://github.com/rails/sdoc.git", branch: "main"
gem "websocket-client-simple", github: "matthewd/websocket-client-simple", branch: "close-race", require: false
